// models/menuItem.js - Class-based model for menu items

// Enum for menu item types
const { logger } = require("../logger/FirebaseLogger");
const ItemType = Object.freeze({
  APPETIZER: "appetizer",
  MAIN: "main",
  DESSERT: "dessert",
  BEVERAGE: "beverage",
  SIDE: "side",
  SPECIAL: "special",
});

// Enum for common allergens
const Allergen = Object.freeze({
  GLUTEN: "gluten",
  DAIRY: "dairy",
  EGGS: "eggs",
  NUTS: "nuts",
  PEANUTS: "peanuts",
  SHELLFISH: "shellfish",
  FISH: "fish",
  SOY: "soy",
  WHEAT: "wheat",
});

/**
 * Class representing a menu item
 */
class MenuItem {
  /**
   * Creates an instance of MenuItem.
   * @param {string} id - The ID of the menu item (optional, generated by Firestore).
   * @param {string} name - The name of the menu item.
   * @param {string} description - The description of the menu item.
   * @param {number} price - The price of the menu item.
   * @param {string} type - The type of the menu item (from ItemType enum).
   * @param {number} calories - The calories of the menu item (optional).
   * @param {number} avgWaitTime - The average wait time in minutes (optional).
   * @param {Array<string>} allergens - List of allergens present (optional).
   * @param {string} imageUrl - URL to the image of the menu item (optional).
   * @param {Date} createdAt - When the menu item was created (optional).
   * @param {Date} updatedAt - When the menu item was last updated (optional).
   */
  constructor(
    id = null,
    name,
    description = null,
    price,
    type,
    calories = null,
    avgWaitTime = null,
    allergens = [],
    imageUrl = null,
    createdAt = null,
    updatedAt = null
  ) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.price = price;
    this.type = type;
    this.calories = calories;
    this.avgWaitTime = avgWaitTime;
    this.allergens = allergens;
    this.imageUrl = imageUrl;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  /**
   * Convert instance to Firestore-compatible format.
   * @param {admin.firestore} admin - Firebase admin instance for timestamps.
   * @returns {Object} Firestore data.
   */
  toFirestore() {
    const data = {
      name: this.name,
      description: this.description,
      price: this.price,
      type: this.type,
      allergens: this.allergens || [],
    };

    // Add optional fields only if they exist
    if (this.calories !== null) data.calories = this.calories;
    if (this.avgWaitTime !== null) data.avgWaitTime = this.avgWaitTime;
    if (this.imageUrl) data.imageUrl = this.imageUrl;

    // Add timestamps
    if (!this.createdAt && !this.id) {
      data.createdAt = Date.now();
    } else if (this.createdAt) {
      data.createdAt = this.createdAt;
    }

    data.updatedAt = Date.now();

    return data;
  }

  /**
   * Populate instance from Firestore snapshot.
   * @param {Object} snapshot - Firestore snapshot.
   * @returns {MenuItem} MenuItem instance.
   */
  static fromFirestore(snapshot) {
    const id = snapshot.id;
    const data = snapshot.data();

    return new MenuItem(
      id,
      data.name,
      data.description,
      data.price,
      data.type,
      data.calories || null,
      data.avgWaitTime || null,
      data.allergens || [],
      data.imageUrl || null,
      data.createdAt ? data.createdAt : null,
      data.updatedAt ? data.updatedAt : null
    );
  }

  /**
   * Create a new MenuItem from request body
   * @param {Object} data - Request body data
   * @returns {MenuItem} New MenuItem instance
   */
  static fromRequestBody(data) {
    let allergens;

    // Handle allergens properly
    if (data.allergens) {
      allergens = typeof data.allergens === "string" ? JSON.parse(data.allergens) : data.allergens;
    } else {
      allergens = [];
    }
    logger.log("info", "MenuItem.fromRequestBody: allergens: ", data);
    return new MenuItem(
      null,
      data.name,
      data.description,
      parseFloat(data.price),
      data.type,
      data.calories ? parseInt(data.calories) : null,
      data.avgWaitTime ? parseInt(data.avgWaitTime) : null,
      allergens,
      data.imageUrl || null
    );
  }

  /**
   * Convert to JSON-friendly format
   * @returns {Object} Plain object representation
   */
  toJSON() {
    return {
      id: this.id,
      name: this.name,
      description: this.description,
      price: this.price,
      type: this.type,
      calories: this.calories,
      avgWaitTime: this.avgWaitTime,
      allergens: this.allergens,
      imageUrl: this.imageUrl,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
    };
  }
}

module.exports = { MenuItem, ItemType, Allergen };
