const { logger } = require("../logger/FirebaseLogger");
const MenuItemService = require("../services/menuItem.service");
// Enum for delivery methods
const DeliveryMethod = Object.freeze({
    HOME_DELIVERY: 'home_delivery',
    PICKUP: 'pickup'
});

// Enum for payment methods
const PaymentMethod = Object.freeze({
    ONLINE: 'online',
    CASH_ON_DELIVERY: 'cash_on_delivery',
    IN_STORE: 'in_store'
});

// Enum for order statuses
const OrderStatus = Object.freeze({
    PENDING_PAYMENT: 'pending_payment',
    PAID: 'paid',
    IN_PROGRESS: 'in_progress',
    READY_FOR_PICKUP: 'ready_for_pickup',
    OUT_FOR_DELIVERY: 'out_for_delivery',
    COMPLETED: 'completed',
    CANCELED: 'canceled'
});

/**
 * Class representing an order
 */
class Order {
    /**
     * Creates an instance of Order.
     * @param {string} id - The ID of the order (optional, generated by Firestore).
     * @param {string} userId - The ID of the user placing the order.
     * @param {Array<Object>} items - Array of menu items in the order, each with id, quantity, and price.
     * @param {number} subtotal - The subtotal of the order before taxes and fees.
     * @param {number} tax - The tax amount for the order.
     * @param {number} deliveryFee - The delivery fee (if applicable).
     * @param {number} total - The total amount of the order.
     * @param {string} deliveryMethod - The delivery method (from DeliveryMethod enum).
     * @param {string} paymentMethod - The payment method (from PaymentMethod enum).
     * @param {string} status - The status of the order (from OrderStatus enum).
     * @param {Object} deliveryAddress - The delivery address (if applicable).
     * @param {string} paymentIntentId - The Stripe payment intent ID (if applicable).
     * @param {Date} createdAt - When the order was created (optional).
     * @param {Date} updatedAt - When the order was last updated (optional).
     * @param {Date} estimatedDeliveryTime - The estimated delivery/pickup time.
     */
    constructor(
        id = null,
        userId,
        items,
        subtotal,
        tax,
        deliveryFee = 0,
        total,
        deliveryMethod,
        paymentMethod,
        status = OrderStatus.PENDING_PAYMENT,
        deliveryAddress = null,
        paymentIntentId = null,
        createdAt = null,
        updatedAt = null,
        estimatedDeliveryTime = null
    ) {
        this.id = id;
        this.userId = userId;
        this.items = items;
        this.subtotal = subtotal;
        this.tax = tax;
        this.deliveryFee = deliveryFee;
        this.total = total;
        this.deliveryMethod = deliveryMethod;
        this.paymentMethod = paymentMethod;
        this.status = status;
        this.deliveryAddress = deliveryAddress;
        this.paymentIntentId = paymentIntentId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.estimatedDeliveryTime = estimatedDeliveryTime;
    }

    /**
     * Convert instance to Firestore-compatible format.
     * @param {admin.firestore} admin - Firebase admin instance for timestamps.
     * @returns {Object} Firestore data.
     */
    toFirestore(admin) {
        const data = {
            userId: this.userId,
            items: this.items,
            subtotal: this.subtotal,
            tax: this.tax,
            deliveryFee: this.deliveryFee,
            total: this.total,
            deliveryMethod: this.deliveryMethod,
            paymentMethod: this.paymentMethod,
            status: this.status
        };

        // Add optional fields only if they exist
        if (this.deliveryAddress) data.deliveryAddress = this.deliveryAddress;
        if (this.paymentIntentId) data.paymentIntentId = this.paymentIntentId;
        if (this.estimatedDeliveryTime) data.estimatedDeliveryTime = this.estimatedDeliveryTime;

        // Add timestamps
        if (!this.createdAt && !this.id) {
            data.createdAt = Date.now();
        } else if (this.createdAt) {
            data.createdAt = this.createdAt;
        }

        data.updatedAt = Date.now();

        return data;
    }

    /**
     * Populate instance from Firestore snapshot.
     * @param {Object} snapshot - Firestore snapshot.
     * @returns {Order} Order instance.
     */
    static fromFirestore(snapshot) {
        const id = snapshot.id;
        const data = snapshot.data();

        return new Order(
            id,
            data.userId,
            data.items,
            data.subtotal,
            data.tax,
            data.deliveryFee || 0,
            data.total,
            data.deliveryMethod,
            data.paymentMethod,
            data.status,
            data.deliveryAddress || null,
            data.paymentIntentId || null,
            data.createdAt ? data.createdAt : null,
            data.updatedAt ? data.updatedAt : null,
            data.estimatedDeliveryTime || null
        );
    }

    /**
     * Create a new Order from request body
     * @param {Object} data - Request body data
     * @returns {Order} New Order instance
     */
    static fromRequestBody(data, userId) {
        logger.log("info", "Order.fromRequestBody: data: ", data);

        // Calculate the subtotal
        const subtotal = data.items.reduce((sum, item) => {
            return sum + (item.price * item.quantity);
        }, 0);

        // Calculate tax (assuming 8% tax rate)
        const taxRate = 0.08;
        const tax = subtotal * taxRate;

        // Calculate delivery fee (if applicable)
        const deliveryFee = data.deliveryMethod === DeliveryMethod.HOME_DELIVERY ? 5.00 : 0;

        // Calculate total
        const total = subtotal + tax + deliveryFee;

        return new Order(
            null,
            userId,
            data.items,
            subtotal,
            tax,
            deliveryFee,
            total,
            data.deliveryMethod,
            data.paymentMethod,
            OrderStatus.PENDING_PAYMENT,
            data.deliveryAddress || null,
            null, // paymentIntentId will be added after Stripe payment is initiated
            null, // createdAt will be set in toFirestore
            null, // updatedAt will be set in toFirestore
            null  // estimatedDeliveryTime will be set later when order is in progress
        );
    }

    /**
     * Convert to JSON-friendly format
     * @returns {Object} Plain object representation
     */
    toJSON() {
        return {
            id: this.id,
            userId: this.userId,
            items: this.items,
            subtotal: this.subtotal,
            tax: this.tax,
            deliveryFee: this.deliveryFee,
            total: this.total,
            deliveryMethod: this.deliveryMethod,
            paymentMethod: this.paymentMethod,
            status: this.status,
            deliveryAddress: this.deliveryAddress,
            paymentIntentId: this.paymentIntentId,
            createdAt: this.createdAt,
            updatedAt: this.updatedAt,
            estimatedDeliveryTime: this.estimatedDeliveryTime
        };
    }

    /**
     * Validates the required fields based on delivery and payment methods
     * @returns {Object} Object with isValid and message properties
     */
    async validate() {
        // Check if we have all the required basic fields
        if (!this.userId || !this.items || this.items.length === 0 || !this.deliveryMethod || !this.paymentMethod) {
            return {isValid: false, message: "Missing required order fields"};
        }

        // Validate item structure
        for (const item of this.items) {
            if (!item.id || !item.quantity || !item.price) {
                return {isValid: false, message: "Invalid item structure in order"};
            }
        }

        // validate prive with quantity
        for (const item of this.items) {
            if (item.price < 0 || item.quantity < 0) {
                return {isValid: false, message: "Invalid price or quantity"};
            }
        }

        // Validate with menu items from database
        const menuItemIds = this.items.map(item => item.id);
        try {
            for (const item of menuItemIds) {
                const menuItem = await MenuItemService.getMenuItemById(item);
                if (!menuItem) {
                    return {isValid: false, message: "Invalid menu item ID"};
                }

                // validate priove with menu item price
                const menuItemPrice = menuItem.price;
                const orderItem = this.items.find(i => i.id === item);
                if (menuItemPrice !== orderItem.price) {
                    return {isValid: false, message: "Invalid price for menu item"};
                }
            }
        } catch (error) {
            return {isValid: false, message: "Failed to retrieve menu items"};
        }


        // Validate payment method based on delivery method
        if (this.deliveryMethod === DeliveryMethod.PICKUP) {
            if (![PaymentMethod.ONLINE, PaymentMethod.IN_STORE].includes(this.paymentMethod)) {
                return {isValid: false, message: "Invalid payment method for pickup"};
            }
        } else if (this.deliveryMethod === DeliveryMethod.HOME_DELIVERY) {
            if (![PaymentMethod.ONLINE, PaymentMethod.CASH_ON_DELIVERY].includes(this.paymentMethod)) {
                return {isValid: false, message: "Invalid payment method for home delivery"};
            }

            // Check for delivery address when home delivery is selected
            if (!this.deliveryAddress) {
                return {isValid: false, message: "Delivery address is required for home delivery"};
            }

            const { street, city, county, eirCode, country } = this.deliveryAddress;
            if (!street || !city || !county || !eirCode || !country) {
                return {isValid: false, message: "Incomplete delivery address"};
            }
        } else {
            return {isValid: false, message: "Invalid delivery method"};
        }

        return {isValid: true, message: "Order is valid"};
    }
}

module.exports = { Order, DeliveryMethod, PaymentMethod, OrderStatus };