name: Check & deploy API documentation
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - release
      - develop
  pull_request:
    branches:
      - release
      - develop
jobs:
  deploy-doc:
    if: ${{ github.event_name == 'push' }}
    name: Deploy API documentation on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Set your project's Node version here

      - name: Install dependencies
        run: npm install

      - name: Generate API documentation (YAML)
        run: node generate-swagger.js
        working-directory: ./functions

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: 49ff646b-a2ae-46b6-91d6-235db15f32ba
          token: ${{ secrets.BUMP_TOKEN }}
          file: ./functions/swagger.yaml

  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Set your project's Node version here

      - name: Install dependencies
        run: npm install

      - name: Generate API documentation (YAML)
        run: node generate-swagger.js
        working-directory: ./functions

      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: 49ff646b-a2ae-46b6-91d6-235db15f32ba
          token: ${{ secrets.BUMP_TOKEN }}
          file: ./functions/swagger.yaml
          command: diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
